#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

# Kill apache2 if running
pkill apache2

# Edit the Nginx configuration file
chmod 644 /etc/nginx/nginx.conf
sed -i "s/user .*;/user nginx;/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Start Nginx as nginx user
su nginx -c "service nginx start" 
