#!/usr/bin/env bash
# UFW configuration: block all incoming traffic except ports 22, 80, and 443

sudo apt-get update
sudo apt-get install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
sudo ufw status verbose 
