#!/usr/bin/env bash
# Installs Nginx and configures it to serve a page with "Holberton School"

set -e

# Install nginx
apt-get update -y
apt-get install -y nginx

# Update default web page
echo "Holberton School for the win!" > /var/www/html/index.html

# Ensure proper Nginx config is used
sed -i 's|index.nginx-debian.html|index.html|' /etc/nginx/sites-available/default

# Restart Nginx using service (not systemctl)
service nginx restart
